version: '3.9'
services:
  ui:
    container_name: crontab-ui
    image: alseambusher/crontab-ui
    depends_on:
      - api
    ports:
      - 8000:8000
    networks:
      - crontab
  api:
    container_name: crontab-api
    build:
      context: .
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    ports:
      - 3333:3333
    networks:
      - crontab
networks:
  crontab:
