version: '3.9'
services:
  cron-ui:
    container_name: cron-ui
    image: alseambusher/crontab-ui
    depends_on:
      - api
    ports:
      - '8000:8000'
    networks:
      - cron-ui
  api:
    container_name: cron-ui-api
    build:
      context: .
      target: builder
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3333:3333
    command: npm start
    networks:
      - cron-ui
networks:
  cron-ui:
